export const blankAvatar = require("./avatar.png")
export const angryIcon = require("./angryIcon.png")
export const heartIcon = require("./heartIcon.png")
export const laughIcon = require("./laughIcon.png")
export const likeIcon = require("./likeIcon.png")
export const sadIcon = require("./sadIcon.png")
export const wowIcon = require("./wowIcon.png")
